"use client";
import Image from "next/image";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Protected } from "@/components/site-shell";
import { Button, Card, Field, Input, Select } from "@/components/ui";
import { useAuth } from "@/providers/app-providers";
import { api } from "@/services/api";
export default function ProfilePage(){const{user,refresh}=useAuth();const[form,setForm]=useState({name:"",avatar:"",experienceLevel:"Intermediate",budget:"Flexible",outputPreference:"Practical and concise"});const[loading,setLoading]=useState(false);useEffect(()=>{if(user)setForm(value=>({...value,name:user.name,avatar:user.avatar||""}))},[user]);const submit=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);try{await api.patch("/users/me",{name:form.name,avatar:form.avatar||undefined,preferences:{experienceLevel:form.experienceLevel,budget:form.budget,outputPreference:form.outputPreference}});await refresh();toast.success("Profile updated")}catch(error){toast.error(error instanceof Error?error.message:"Update failed")}finally{setLoading(false)}};return <Protected><div className="container max-w-3xl py-10"><h1 className="text-3xl font-black">Your profile</h1><p className="mt-2 text-slate-500">Update your identity and recommendation defaults.</p><Card className="mt-8 p-6 md:p-8"><div className="mb-7 flex items-center gap-4"><Image src={form.avatar||`https://api.dicebear.com/9.x/initials/svg?seed=${form.name||"User"}`} width={72} height={72} alt="Profile" className="rounded-2xl"/><div><strong className="text-lg">{user?.name}</strong><span className="block text-sm text-slate-400">{user?.email}</span><span className="mt-1 inline-flex rounded-full bg-lavender px-2 py-0.5 text-xs font-bold text-brand">{user?.role}</span></div></div><form onSubmit={submit} className="grid gap-5 sm:grid-cols-2"><Field label="Name"><Input required minLength={2} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Avatar URL"><Input type="url" value={form.avatar} onChange={e=>setForm({...form,avatar:e.target.value})} placeholder="https://…"/></Field><Field label="Experience level"><Select value={form.experienceLevel} onChange={e=>setForm({...form,experienceLevel:e.target.value})}>{["Beginner","Intermediate","Advanced"].map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="Budget"><Select value={form.budget} onChange={e=>setForm({...form,budget:e.target.value})}>{["Free","$1-$20","Flexible"].map(x=><option key={x}>{x}</option>)}</Select></Field><div className="sm:col-span-2"><Field label="Output preference"><Select value={form.outputPreference} onChange={e=>setForm({...form,outputPreference:e.target.value})}>{["Practical and concise","Detailed explanation","Creative options","Data-driven"].map(x=><option key={x}>{x}</option>)}</Select></Field></div><div className="sm:col-span-2"><Button loading={loading}>Save profile</Button></div></form></Card></div></Protected>}
