"use client";
import { LoaderCircle, SearchX, X } from "lucide-react";
import { type ButtonHTMLAttributes, type InputHTMLAttributes, type ReactNode } from "react";
import { cn } from "@/lib/utils";

export function Button({ className, variant = "primary", loading, children, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "ghost" | "danger"; loading?: boolean }) {
  const variants = { primary: "bg-brand text-white shadow-brand hover:-translate-y-0.5", secondary: "border border-brand/20 bg-white text-brand hover:bg-lavender", ghost: "text-navy hover:bg-lavender", danger: "bg-red-600 text-white hover:bg-red-700" };
  return <button className={cn("inline-flex h-11 items-center justify-center gap-2 rounded-xl px-5 text-sm font-semibold transition disabled:cursor-not-allowed disabled:opacity-55", variants[variant], className)} disabled={loading || props.disabled} {...props}>{loading && <LoaderCircle className="size-4 animate-spin" />}{children}</button>;
}
export function Input({ className, ...props }: InputHTMLAttributes<HTMLInputElement>) { return <input className={cn("h-11 w-full rounded-xl border border-slate-200 bg-white px-3.5 text-sm outline-none transition placeholder:text-slate-400 focus:border-brand focus:ring-4 focus:ring-brand/10", className)} {...props} />; }
export function Textarea({ className, ...props }: React.TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea className={cn("min-h-32 w-full resize-y rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm outline-none transition placeholder:text-slate-400 focus:border-brand focus:ring-4 focus:ring-brand/10", className)} {...props} />; }
export function Select({ className, ...props }: React.SelectHTMLAttributes<HTMLSelectElement>) { return <select className={cn("h-11 w-full rounded-xl border border-slate-200 bg-white px-3.5 text-sm outline-none focus:border-brand focus:ring-4 focus:ring-brand/10", className)} {...props} />; }
export function Card({ className, children }: { className?: string; children: ReactNode }) { return <div className={cn("rounded-2xl border border-slate-200/80 bg-white shadow-card", className)}>{children}</div>; }
export function Badge({ children, className }: { children: ReactNode; className?: string }) { return <span className={cn("inline-flex rounded-full bg-lavender px-2.5 py-1 text-xs font-semibold text-brand", className)}>{children}</span>; }
export function Skeleton({ className }: { className?: string }) { return <div className={cn("animate-pulse rounded-xl bg-slate-200", className)} />; }
export function EmptyState({ title = "Nothing here yet", description = "Try changing your filters or create something new.", action }: { title?: string; description?: string; action?: ReactNode }) { return <div className="col-span-full flex min-h-60 flex-col items-center justify-center rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-center"><span className="mb-4 grid size-12 place-items-center rounded-2xl bg-lavender text-brand"><SearchX /></span><h3 className="font-bold text-navy">{title}</h3><p className="mt-2 max-w-md text-sm text-slate-500">{description}</p>{action && <div className="mt-5">{action}</div>}</div>; }
export function ErrorState({ message, retry }: { message: string; retry?: () => void }) { return <EmptyState title="We couldn't load this" description={message} action={retry && <Button onClick={retry}>Try again</Button>} />; }
export function Modal({ open, title, children, onClose }: { open: boolean; title: string; children: ReactNode; onClose: () => void }) { if (!open) return null; return <div className="fixed inset-0 z-[100] grid place-items-center bg-navy/50 p-4 backdrop-blur-sm" onMouseDown={onClose}><Card className="w-full max-w-md p-6" ><div onMouseDown={(e) => e.stopPropagation()}><div className="mb-5 flex items-center justify-between"><h3 className="text-lg font-bold">{title}</h3><button aria-label="Close modal" onClick={onClose}><X /></button></div>{children}</div></Card></div>; }
export function Field({ label, error, children }: { label: string; error?: string; children: ReactNode }) { return <label className="block"><span className="mb-1.5 block text-sm font-semibold text-navy">{label}</span>{children}{error && <span className="mt-1 block text-xs text-red-600">{error}</span>}</label>; }
